### ISSUE TITLE
thank you for your good job，some questions

### ISSUE THREAD

**Issue by angeluau** [kururuken/BERT-Transformer-for-Summarization#1]
1.which version Bert pretrained models did you apply?can you show the linked url;
2.can you show the order of action the data.py, i dont know how to produce the train.csv  and eval.csv, is there  remain valid.csv?
3.when i use the files in bert_model ,show the error ,no such file(No such file or directory: 'bert_model\\pytorch_model.bin')

thank your for your reply

**Comment by fangpings** [comment]
Hi, for your questions 
1. I use [bert-base-chinese](https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz), you can find the model in the link above. I am not sure whether this link also contains vocal.txt file. If not, you should download it elsewhere for tokenization.
After you have the model, put it in the directory pretrained_model\. This will also solve your problem 3.
2. I don't know what dataset you use. If you also use LCSTS dataset, you should put the original dataset into data/raw_data directory(or you can put it elsewhere as long as you modify the path in data.py). An organization example like this
```
data
├── processed_data
│   ├── eval.csv
│   ├── train.csv
│   ├── train_big.csv
│   └── train_full.csv
└── raw_data
    ├── DATA
    │   ├── PART_I.txt
    │   ├── PART_II.txt
    │   └── PART_III.txt
    ├── LCSTS\ A\ Large\ Scale\ Chinese\ Short\ Text\ Summarization\ Dataset.pdf
    ├── README_IMPORTANT.txt
    └── Result
        ├── rouge.char_context.txt
        ├── rouge.char_nocontext.txt
        ├── rouge.word_context.txt
        ├── rouge.word_nocontext.txt
        ├── sumary.generated.char.context.txt
        ├── sumary.generated.char.nocontext.txt
        ├── sumary.generated.word.context.txt
        ├── sumary.generated.word.nocontext.txt
        ├── sumary.human.txt
        └── weibo.txt
```
After you put the dataset into correct path, data.py should work.
As for splitting  train.csv, eval.csv and valid.csv, I just change the name of the generated files and rerun data.py.
If you use other dataset like CNN/Daily Mail, you should consider modifying data.py since the format varies a lot.

**Comment by angeluau** [comment]
can you show the last results of rouge
------------------ 原始邮件 ------------------
发件人: "kururuken"<notifications@github.com>;
发送时间: 2019年5月18日(星期六) 晚上7:40
收件人: "kururuken/BERT-Transformer-for-Summarization"<BERT-Transformer-for-Summarization@noreply.github.com>;
抄送: "小太阳"<2215346277@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kururuken/BERT-Transformer-for-Summarization] thank you for your good job，some questions (#1)




Hi, for your questions
  
I use bert-base-chinese, you can find the model in the link above. I am not sure whether this link also contains vocal.txt file. If not, you should download it elsewhere for tokenization.
 After you have the model, put it in the directory pretrained_model. This will also solve your problem 3.
 
I don't know what dataset you use. If you also use LCSTS dataset, you should put the original dataset into data/raw_data directory(or you can put it elsewhere as long as you modify the path in data.py). An organization example like this
  data ├── processed_data │   ├── eval.csv │   ├── train.csv │   ├── train_big.csv │   └── train_full.csv └── raw_data     ├── DATA     │   ├── PART_I.txt     │   ├── PART_II.txt     │   └── PART_III.txt     ├── LCSTS\ A\ Large\ Scale\ Chinese\ Short\ Text\ Summarization\ Dataset.pdf     ├── README_IMPORTANT.txt     └── Result         ├── rouge.char_context.txt         ├── rouge.char_nocontext.txt         ├── rouge.word_context.txt         ├── rouge.word_nocontext.txt         ├── sumary.generated.char.context.txt         ├── sumary.generated.char.nocontext.txt         ├── sumary.generated.word.context.txt         ├── sumary.generated.word.nocontext.txt         ├── sumary.human.txt         └── weibo.txt  
After you put the dataset into correct path, data.py should work.
 As for splitting  train.csv, eval.csv and valid.csv, I just change the name of the generated files and rerun data.py.
 If you use other dataset like CNN/Daily Mail, you should consider modifying data.py since the format varies a lot.

**Comment by fangpings** [comment]
<img width="416" alt="屏幕快照 2019-05-18 下午8 53 08" src="https://user-images.githubusercontent.com/22250698/57970043-00225b00-79af-11e9-8143-a6d233324c99.png">

**Comment by angeluau** [comment]
further question
the code has it's corresponding paper ?
can you share the paper ,thank you guys
taeyanglucky from Guangzhou,China
the code just to practice ,no other application


------------------ 原始邮件 ------------------
发件人: "kururuken"<notifications@github.com>;
发送时间: 2019年5月18日(星期六) 晚上8:54
收件人: "kururuken/BERT-Transformer-for-Summarization"<BERT-Transformer-for-Summarization@noreply.github.com>;
抄送: "小太阳"<2215346277@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kururuken/BERT-Transformer-for-Summarization] thank you for your good job，some questions (#1)

**Comment by fangpings** [comment]
Technically, no. Just a try to use BERT in summarization.
But inspired by this [paper](https://arxiv.org/abs/1902.09243)
