### ISSUE TITLE
how can i get train.csv?

### ISSUE THREAD

**Issue by dreamfuluser** [kururuken/BERT-Transformer-for-Summarization#2]

**Comment by fangpings** [comment]
If you also use LCSTS dataset, please download the original dataset in directory data/raw_data and then run data.py.
You can refer to #1

**Comment by dreamfuluser** [comment]
My GPU is 12G memory，there is a problem that 'out of memory',  is it not enough?

**Comment by fangpings** [comment]
Make batch size smaller, say 20, if you use only 1 card.
