### ISSUE TITLE
TypeError: beam_decode() missing 2 required positional arguments: 'beam_size' and 'n_best'

### ISSUE THREAD

**Issue by jufengada** [kururuken/BERT-Transformer-for-Summarization#6]
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    pred, _ = model.beam_decode(batch[0], batch[1])
TypeError: beam_decode() missing 2 required positional arguments: 'beam_size' and 'n_best'

**Comment by wangDong524** [comment]
hi,Have you solved the problem,I had the same problem。
thank you
